name: OpenAPI Validate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (for npx)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Sanity – list repo
        run: ls -la

      - name: Lint OpenAPI if present
        shell: bash
        run: |
          set -euo pipefail
          FILE="openapi.yaml"
          if [[ ! -f "$FILE" ]]; then
            echo "::warning title=openapi.yaml not found::Skipping lint"; exit 0
          fi
          npx -y @redocly/cli@latest lint "$FILE"
